name: Build Unity Project

on:
  push:
    branches:
      - use-choosed-rocket-in-mission
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Unity project for Windows
      uses: game-ci/unity-builder@v2
      with:
        target-platform: standalone
        target-platform-version: 10.0.19041
        unity-version: 2021.1.25f1
        project-path: logiciel
        build-name: WindowsBuild.exe
        build-path: Build/windows/
        build-method: build
        build-options: ''
        custom-args: ''
        project-version-file: logiciel/ProjectSettings/ProjectVersion.txt

    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: Build/windows

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: List ProjectSettings folder contents
      run: ls logiciel/ProjectSettings/
    
    - name: Build Unity project for Linux
      uses: game-ci/unity-builder@v2
      with:
        target-platform: standalone
        target-platform-version: linux
        unity-version: 2021.1.25f1
        project-path: logiciel
        build-name: LinuxBuild
        build-path: Build/linux/
        build-method: build
        build-options: ''
        custom-args: ''
        project-version-file: logiciel/ProjectSettings/ProjectVersion.txt

    - name: Upload Linux build artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: Build/linux
